// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe86LsduWrSMWDuEt3Oe6Kc4_kGYllVZk',
    appId: '1:420748776319:android:4d903c698d6ebbdd71804a',
    messagingSenderId: '420748776319',
    projectId: 'todo-app-abf16',
    databaseURL: 'https://todo-app-abf16-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-abf16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-RQsm7R-B4AbfuBFm8f-HKKdYUVbRFhQ',
    appId: '1:420748776319:ios:5ad208d875d1a1a771804a',
    messagingSenderId: '420748776319',
    projectId: 'todo-app-abf16',
    databaseURL: 'https://todo-app-abf16-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'todo-app-abf16.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
}
